spring:
  data:
    solr:
      zk-host: 127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183/solr
    repositories:
      enabled: true
#    host: http://192.168.56.101:8983/solr

logging:
  config: classpath:log4j2-dev.xml

app:
  solr:
    auto-commit: true

swagger:
  show: true