server:
  port: 6001
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          # 配置git仓库的地址
          uri: https://github.com/yaloo/spring-cloud-tester
          # git仓库地址下的相对地址，可以配置多个，用,分割。
          search-paths: config-repo/
          username:
          password:
    #跟踪总线事件
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
#    username: guest
#    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/,http://peer3:8002/eureka/   # 注册中心eurka地址

management:
  security:
     enabled: false